### ISSUE TITLE
Examples?

### ISSUE THREAD

**Issue by feldon30** [gabriel-milan/TinyMPU6050#1]
Thank you for posting this. However I find no Arduino or AVR code examples on the use of this library.

**Comment by gabriel-milan** [comment]
Hi @feldon30, thanks for posting!

You can find a basic example on how showing angles here: https://github.com/gabriel-milan/TinyMPU6050/tree/master/examples/PlatformIO_Angles_Example

It's a PlatformIO (https://platformio.org/) project, as I use VSCode for coding, but if you just copy/paste the code at https://github.com/gabriel-milan/TinyMPU6050/blob/master/examples/PlatformIO_Angles_Example/src/main.cpp on your Arduino IDE or whatever, it should work.

Anyway, if you need a specific kind of example code, just let me know and I'll post it ASAP.

**Comment by feldon30** [comment]
Thank you kindly.
