### ISSUE TITLE
All Gets Example doesn't compile, GetAngAccZ missing

### ISSUE THREAD

**Issue by pavitter-bluestone** [gabriel-milan/TinyMPU6050#15]
Hey there,
I pulled the current master and noticed that the PlatformIO_All_Gets_Example doesn't compile, because the function GetAngAccZ is missing since the commit: 5264a0dad3928230909409999ad4b670e8cba899 .
The Arduino_All_Gets_Example has the same problem too.
Hope it helps.

**Comment by gabriel-milan** [comment]
Thank you so much for that, @pavitter-bluestone 
This issue's been fixed on 4fc9b0b2fff5af939642140b1150b8d5cf6c6d1e.
If you need anything else please let me know.
