### ISSUE TITLE
Prints out same values regardless of sensor position

### ISSUE THREAD

**Issue by Technerder** [gabriel-milan/TinyMPU6050#2]
I am using the example sketch, with the pin configuration:

SDA -> A5 
SCL -> A4

However, regardless of how I move the gyroscope, the same values are printed out.

The output of the program can be found below

`
=====================================
Starting calibration...
Calibration complete!
Offsets:
AccX Offset = 0.00
AccY Offset = 0.00
AccZ Offset = 2047.00
GyroX Offset = 0.00
GyroY Offset = 0.00
GyroZ Offset = 0.00
AngX = 179.99  /  AngY = 179.99  /  AngZ = 45.00
AngX = 179.99  /  AngY = 179.99  /  AngZ = 45.00
AngX = 179.99  /  AngY = 179.99  /  AngZ = 45.00
AngX = 179.99  /  AngY = 179.99  /  AngZ = 45.00
AngX = 179.99  /  AngY = 179.99  /  AngZ = 45.00
AngX = 179.99  /  AngY = 179.99  /  AngZ = 44.99
AngX = 179.99  /  AngY = 179.99  /  AngZ = 44.99
AngX = 179.99  /  AngY = 179.99  /  AngZ = 44.99
AngX = 179.99  /  AngY = 179.99  /  AngZ = 44.99
AngX = 179.99  /  AngY = 179.99  /  AngZ = 44.99
AngX = 179.99  /  AngY = 179.99  /  AngZ = 44.99
AngX = 179.99  /  AngY = 179.99  /  AngZ = 44.99
`

**Comment by gabriel-milan** [comment]
Hi @Technerder, thanks for posting!

As you can see in the Arduino Uno pinout (I'm assuming it's an UNO for your pin configuration), the correct configuration is:
- A4 --> SDA
- A5 --> SCL

Source: https://www.theengineeringprojects.com/wp-content/uploads/2018/06/Introduction-to-Arduino-UNO.png

If anything else goes wrong, please let me know!
