### ISSUE TITLE
Initial orientation

### ISSUE THREAD

**Issue by intensite** [gabriel-milan/TinyMPU6050#22]
Hello Gabriel, 

I just discovered your library today and it looks promising.

I am wondering what should be changed in the MPU6050::Execute() function, to take into consideration when the IMU is mounted vertically (with the Y axis pointing up/down instead of the Z-Axis).

I think the calculation of the angleAccZ and angleZ variables should take gravity into consideration instead of Y axis in this condition.

**Comment by gabriel-milan** [comment]
Hi @intensite, thanks for writing.

I don't think this should be an issue if, during the calibration process, the MPU is set to whatever position you'd like. But anyway, if that's the case, you could try the new implementation of the calibration method on the [dev branch](https://github.com/gabriel-milan/TinyMPU6050/tree/dev). Maybe that would solve things for you.
