### ISSUE TITLE
Library Install from Arduino IDE

### ISSUE THREAD

**Issue by foxalabs** [gabriel-milan/TinyMPU6050#3]
If you install from the Arduino IDE, you still get the example versions with the "mpu." missing from the function calls in the ArduinoIDE_All_Gets_Example, dunno if that's the library people being slow, or if its some date/time stamp thing not detecting it as a new version <insert shrug emote>

**Comment by gabriel-milan** [comment]
Hi @foxabilo, thanks for posting!

That's my bad actually, I forgot to launch a release after fixing the examples from release 0.4.2.
Anyway, I've just done it, hope it'll be available as soon as possible!

Thanks!
