### ISSUE TITLE
ArduinoIDE_All_Gets_Example missing mpu.Execute();

### ISSUE THREAD

**Issue by foxalabs** [gabriel-milan/TinyMPU6050#5]
Last one I promise!

ArduinoIDE_All_Gets_Example is missing the mpu.Execute(); call so the info you see is the last one received by the calibration call and it does not change.

**Comment by gabriel-milan** [comment]
Hi @foxabilo!

> Last one I promise!

Please, post as you wish! Every new issue is making this library better.
I've just fixed the examples but will wait for the issue #6 to be fixed in order to launch a new release.

Thanks!
