### ISSUE TITLE
Updating to V0.4.3

### ISSUE THREAD

**Issue by foxalabs** [gabriel-milan/TinyMPU6050#7]
After using the built in Arduino IDE update library function to V 0.4.3 the following is received in the debug window

`Invalid library found in C:\Users\<user name>\OneDrive\Documents\Arduino\libraries\TinyMPU6050: no headers files (.h) found in C:\Users\<user name>\OneDrive\Documents\Arduino\libraries\TinyMPU6050`

This may be a OneDrive path issue, but deleting the library manually and then manually putting the downloaded extracted zip version from GitHub fixes the issue.

**Comment by gabriel-milan** [comment]
Hi @foxabilo!

This is probably a path issue, something that's not uncommon on Windows machines. My personal recommendation is, if you really want to develop on Windows, that you use VSCode (https://code.visualstudio.com/) + PlatformIO extension for VSCode (https://platformio.org/) on your machine.

**Comment by foxalabs** [comment]
Owww, that looks shiny... I am ripping my hair out with Arduino IDE, it reminds me of borland turbo pascal with the DOS interface
